# Generated by Django 3.1.2 on 2021-05-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('modified_time', models.CharField(default='05-01-2021 07:07:50 AM', max_length=50)),
                ('blocked', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='Users.User')),
            ],
        ),
    ]
