# Generated by Django 3.1.2 on 2021-05-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_time',
            field=models.CharField(default='05-01-2021 07:07:02 AM', max_length=50),
        ),
    ]
